# Generated by Django 2.2.1 on 2021-08-13 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DigilockerUserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digilockerid', models.CharField(db_index=True, max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F'), ('T', 'T')], max_length=1, null=True)),
                ('eaadhaar_available', models.BooleanField(default=False)),
                ('reference_key', models.CharField(max_length=70, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IssuedDocsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('mime', models.CharField(max_length=16, null=True)),
                ('uri', models.CharField(max_length=64)),
                ('digilocker_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='digilocker.DigilockerUserDetails')),
            ],
        ),
    ]
